---
    - name: Pull portainer Docker image
      docker_image:
        name: "portainer/portainer"
        source: pull
        
    - name: Remove portainer
      docker_container:
        name: portainer
        state: absent

    # RETRIEVE VOLUMES STATUS
    - name: Check volumes (portainer_data)
      docker_volume_info:
        name: portainer_data
      register: portainer_data_exist

    # CREATE VOLUMES IF NECESSARY
    - name: Create portainer_data volume 
      docker_volume:
        name: portainer_data
      when: portainer_data_exist.exists

  
    # INSTALL PORTAINER
    - name: Install Portainer.io
      docker_container:
        name: portainer
        image: portainer/portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        ports:
            - "{{docker_portainer_port_9000}}:9000"
            - "{{docker_portainer_port_8000}}:8000"
        state: started
        restart_policy: always
        recreate: yes

