- name: Add Odoo Apt signing key
  apt_key:
    url: https://nightly.odoo.com/odoo.key
    state: present

- name: Add Odoo 12 repository
  apt_repository:
    repo: deb http://nightly.odoo.com/12.0/nightly/deb/ ./
    state: present

- name: Software dependencies
  apt:
    name:
      - odoo
      - git
      - wkhtmltopdf
      - sudo
    update_cache: yes
    state: latest

- name: Suppression de postgresql server
  apt:
    name:
      - postgresql
      - postgresql-{{ postgresql_version }}
    update_cache: yes
    state: absent
