stages:
  - tests
  - build

variables:
  ANSIBLE714_VERSION: '0.1.0'

#-----------------------------------------
# Need some tests

ansible_linting:
  stage: tests
  tags:
    - docker
  image: python:3.8-buster
  script:
    - pip3 install -r requirements_dev.txt
    - ansible-lint


ansible_testting:
  stage: tests
  tags: 
    - docker
  image: python:3.8-buster
  services:
    - name: ubuntu:20.04
      alias: target
  script:
    - pip3 install -r requirements_dev.txt


#-----------------------------------------
# Trigger 

trigger_build_image:
  stage: build
  trigger: 
    project: article714/ansible714-docker
    branch: ${CI_COMMIT_BRANCH}
    strategy: depend
