stages:
  - tests
  - build

variables:
  ANSIBLE714_VERSION: '0.1.0'

#-----------------------------------------
# Need some tests

ansible_linting:
  stage: tests
  tags:
    - docker
  image: python:3.8-buster
  script:
    - pip3 install -r requirements_dev.txt
    - /bin/bash scripts/init_dependencies.sh
    - ansible-lint


ansible_testing_simple_playbook:
  stage: tests
  tags: 
    - docker
  image: python:3.8-buster
  script:
    - pip3 install -r requirements_dev.txt
    - /bin/bash scripts/init_dependencies.sh
    - ansible-playbook -i tests/target.yml update-software.yml

#-----------------------------------------
# Trigger 

trigger_build_image:
  stage: build
  only:
    refs:
      - production
      - master
  trigger: 
    project: article714/ansible714-docker
    branch: ${CI_COMMIT_BRANCH}
    strategy: depend
