# setup a basic nft firewall
#

- name: enable NFTables service
  systemd:
    name: nftables
    enabled: yes
    masked: no


- name: apply NFTables role from IPR-CNRS
  include_role:
    name: ipr-cnrs.nftables
  