# setup a basic nft firewall
#

- name: enable NFTables service
  systemd:
    name: nftables
    enabled: yes
    masked: no

- name: copy Custom NFT files
  copy:
    src: "{{ inventory_dir }}/files/{{ inventory_hostname }}/nftables/"
    dest: "/etc/nftables.d/"
    owner: root
    group: root
    mode: '0644'

- name: apply NFTables role from IPR-CNRS
  include_role:
    name: ipr-cnrs.nftables
