- name: enable packet forwarding so that we can efficiently use bridges
  sysctl:
    name: '{{ item }}'
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.forwarding
    - net.ipv4.ip_forward
  when: routing_enabled|bool
