---
- name: Install Gitlab Runner
  apt:
    name: gitlab-runner
    state: present
  notify:
    - Start gitlab-runner

- name: make gitlab-runner certs dir
  file:
    path: '/etc/gitlab-runner/certs'
    owner: gitlab-runner
    group: gitlab-runner
    mode: '0770'
    state: directory
