galaxy_info:
  author: C. Guychard <christophe@article714.org>
  description: Manage Let's encrypt Certificates
  company: Article714

  license: LGPL

  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - system
    - webserver
    - apache
    - nginx
    - haproxy
    - debian
    - ubuntu

