---
    - name: Pull portainer Docker image
      docker_image:
        name: "portainer/portainer"
        source: pull
        
    - name: Remove portainer
      docker_container:
        name: portainer
        state: absent
  
    - name: Install Portainer.io
      docker_container:
        name: portainer
        image: portainer/portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data portainer/portainer
        ports:
            - "9000:9000"
            - "8000:8000"
