---
- include: filesystem.yml

- name: Setup Let's Encrypt account key
  copy:
    remote_src: no
    owner: root
    group: root
    mode: 0644
    backup: no
    src: '{{ ACME_ACCOUNT_KEY.from }}'
    dest: '{{ ACME_ACCOUNT_KEY.to }}'

- name: Ensure we can communicate with ACME server
  get_url:
    url: https://acme-v02.api.letsencrypt.org/directory
    dest: /tmp/acme_dir.html
    mode: '0440'
  retries: 3
  delay: 60

- name: Ensure Let's Encrypt account exists
  acme_account:
    acme_version: 2
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    account_key_src: '{{ ACME_ACCOUNT_KEY.to }}'
    state: present
    terms_agreed: yes
    contact:
      - 'mailto:{{ ACME_ACCOUNT_EMAIL }}'
  when: letsencrypt_enable|default(false)

- name: Check certificates date
  stat:
    path: "{{ letsencrypt_target_dir  }}/live/{{ item.dname }}/fullchain.pem"
    follow: yes
  register: mtimes
  with_items: '{{ acme_domains }}'
  when: letsencrypt_enable|default(false)

- name: Renew Certificates
  include: renew_certificate.yml
  when: (letsencrypt_enable|default(false) and (( not item.stat.exists ) or ( ansible_date_time.epoch|float - item.stat.mtime > 60*60*24*60 )))
  with_items: '{{ mtimes.results }}'

- name: Cleanup when needed
  include: cleanup.yml
  when: letsencrypt_enable|default(false)
