---

- name: Setup Let's Encrypt account key
  copy:
    remote_src: no
    owner: root
    group: root
    mode: 0644
    backup: no
    src: '{{ ACME_ACCOUNT_KEY.from }}'
    dest: '{{ ACME_ACCOUNT_KEY.to }}'

- name: Ensure Let's Encrypt account exists
  acme_account:
    acme_version: 2
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    account_key_src: '{{ ACME_ACCOUNT_KEY.to }}'
    state: present
    terms_agreed: yes
    contact:
      - mailto: '{{ ACME_ACCOUNT_EMAIL }}'
  when: letsencrypt_enable|bool

- include: filesystem.yml

- name: Check certificates date
  stat:
    path: /etc/letsencrypt/live/{{ item.dname }}/fullchain.pem
    follow: yes
  register: mtimes
  with_items: '{{ acme_domains }}'
  when: letsencrypt_enable|bool

- name: Renew Certificates
  include: renew_certificate.yml
  when: (letsencrypt_enable|bool and (( not item.stat.exists ) or ( ansible_date_time.epoch|float - item.stat.mtime > 60*60*24*60 )))
  with_items: '{{ mtimes.results }}'

- name: Cleanup when needed
  include: cleanup.yml
  when: letsencrypt_enable|bool
