galaxy_info:
  author: C. Guychard <christophe@article714.org>, L. Rondel 
  description: Manage HA-Proxy instances 
  company: Article714

  license: LGPL

  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - system
    - workstation
    - debian
    - ubuntu
    - ha-proxy

dependencies:
  - { role: 'debian-based-container', when: machine_type == 'lxd' }
  - { role: 'debian-based-host', when: machine_type == 'host' }