---
- name: Import Docker CE repository gpg key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker CE repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable'
    state: present
  when: ansible_distribution_release != "eoan"
  retries: 3
  delay: 15

# il faudra régler ça lorsque docker sera dispo pour eoan
- name: Add Docker CE repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable'
    state: present
  when: ansible_distribution_release == "eoan"
  retries: 3
  delay: 15
