- name: Stop docker.service
  systemd:
    state: stopped
    name: docker

- name: Creates empty daemon.json file if it does not exist
  file:
    path: /etc/docker/daemon.json
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Override docker conf for docker data dir
  edit_json:
    file: /etc/docker/daemon.json
    updates:
      data-root: '{{ docker_data_dir }}'

- name: Reload daemon and docker.service
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
