
- name: Enable forwarding for Docker bridges
  ufw:
    default: allow
    direction: 'routed'
    interface: '{{ item }}'
  with_items: '{{ docker_bridges }}'

- name: Enable http/https for Docker bridges (OUT)
  ufw:
    rule: allow
    direction: 'out'
    interface: '{{ item[0] }}'
    port: '{{ item[1] }}'
    proto: tcp
  with_nested:
    - '{{ docker_bridges }}'
    - ['http', 'https']

- name: Reload Firewall
  ufw:
    state: reloaded
