- name: Stop docker.service
  systemd:
    state: stopped
    name: docker
  when: restart_docker_daemon | default(True)

- name: Creates empty daemon.json file if it does not exist
  file:
    path: /etc/docker/daemon.json
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Override docker conf for docker data dir
  edit_json:
    file: /etc/docker/daemon.json
    updates:
      data-root: '{{ docker_data_dir }}'
  when: docker_default_dns | default(false)

- name: Override docker conf for docker DNS on bridge network
  edit_json:
    file: /etc/docker/daemon.json
    updates:
      dns: '{{ docker_default_dns }}'
  when: docker_default_dns | default(false)

- name: Setup TLS
  edit_json:
    file: /etc/docker/daemon.json
    updates:
      tls: true
      tlscacert: "{{ docker_tls_cacert }}"
      tlscert: "{{ docker_tls_cert }}"
      tlskey: "{{ docker_tls_key }}"
      tlsverify: true
  when: docker_with_tls | default(false)

- name: Update docker sockets when needed
  lineinfile:
    path: "/lib/systemd/system/docker.service"
    regexp: '^ExecStart=/usr/bin/dockerd .*$'
    state: present
    line: "ExecStart=/usr/bin/dockerd {{ docker_listeners }} --containerd=/run/containerd/containerd.sock"
  when: docker_listeners | default(false)



- name: Reload daemon and docker.service
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  when: restart_docker_daemon | default(True)
