---
# defaults file for odoo-node
ansible_ssh_pipelining: true

odoo_install_type: standard # standard, buildout
odoo_version: 12.0
odoo_service: odoo
odoo_user: odoo
odoo_user_passwd: '*' # http://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
odoo_user_update_password: always
odoo_user_shell: /bin/bash
odoo_user_system: False
odoo_init: True
odoo_init_env:
  {}
  #VAR1: value1
  #VAR2: value2
odoo_logdir: '/var/log/{{ odoo_user }}'
odoo_logfile: "{{ ansible_service_mgr != 'systemd' and ('/'.join([odoo_logdir, odoo_service]) + '.log') or ''}}"
odoo_workdir: '/home/{{ odoo_user }}/odoo'
odoo_rootdir: "{{ odoo_install_type == 'buildout' and '/home/'+odoo_user+'/odoo/parts/odoo' or '/home/'+odoo_user+'/odoo/server' }}"

# Third party programs options
odoo_reportlab_font_url: http://www.reportlab.com/ftp/pfbfer.zip

# Tasks related to PostgreSQL
odoo_postgresql_set_user: True
odoo_postgresql_user_role_attr: CREATEDB,NOSUPERUSER
odoo_postgresql_extensions:
  - unaccent

# Standard installation/configuration options (odoo_install_type == 'standard')
odoo_config_file: '/home/{{ odoo_user }}/{{ odoo_service }}.conf'
odoo_force_config: True
odoo_config_addons_path:
  - '/usr/lib/python3/dist-packages/odoo/addons'
odoo_config_admin_passwd: admin
odoo_config_auto_reload: False
odoo_config_csv_internal_sep: ','
odoo_config_data_dir: '/home/{{ odoo_user }}/data/'
odoo_config_db_host: False
odoo_config_db_host_user: '{{ ansible_user }}'
odoo_config_db_maxconn: 64
odoo_config_db_name: False
odoo_config_db_passwd: False
odoo_config_db_port: False
odoo_config_db_sslmode: prefer # >= 11.0
odoo_config_db_template: template1
odoo_config_db_user: '{{ odoo_user }}'
odoo_config_dbfilter: '.*'
odoo_config_debug_mode: False # <= 9.0
odoo_config_pidfile: None
odoo_config_proxy_mode: False
odoo_config_email_from: False
odoo_config_geoip_database: /usr/share/GeoIP/GeoLiteCity.dat
odoo_config_http_enable: True # >= 11.0
odoo_config_http_interface: '' # >= 11.0
odoo_config_http_port: 8069 # >= 11.0
odoo_config_limit_memory_hard: 2684354560
odoo_config_limit_memory_soft: 2147483648
odoo_config_limit_time_cpu: 60
odoo_config_limit_time_real: 120
odoo_config_limit_time_real_cron: -1 # >= 10.0
odoo_config_list_db: True
odoo_config_log_db: False
odoo_config_log_level: info
odoo_config_logfile: None
odoo_config_logrotate: False
odoo_config_longpolling_port: 8072
odoo_config_osv_memory_age_limit: 1.0
odoo_config_osv_memory_count_limit: False
odoo_config_max_cron_threads: 2
odoo_config_secure_cert_file: server.cert
odoo_config_secure_pkey_file: server.pkey
odoo_config_server_wide_modules: None
odoo_config_smtp_password: False
odoo_config_smtp_port: 25
odoo_config_smtp_server: localhost
odoo_config_smtp_ssl: False
odoo_config_smtp_user: False
odoo_config_syslog: False
odoo_config_timezone: False
odoo_config_translate_modules: "['all']"
odoo_config_unaccent: False
odoo_config_without_demo: False
odoo_config_workers: 0
# Custom configuration options
odoo_config_custom:
  {}
  #your_option1: value1
  #your_option2: value2
