---
- include: dependencies.yml
- include: filesystem.yml
- include: cleanup_config.yml
- include: private_key.yml
- include: ssl_certs.yml
- include: syslog_config.yml
- include: update-dns.yml

- name: configure hostname and domain name
  hostname:
    name: '{{ host_name }}'
  when: "host_name | default(false)"
