# RETRIEVE VOLUMES STATUS
- name: Check volumes (gravitee_mongo_data)
  docker_volume_info:
    name: "gravitee_mongo_data"
  register: gravitee_mongo_data_infos

# CREATE VOLUMES IF NECESSARY
- name: Create  volume gravitee_mongo_data (optional)
  docker_volume:
    name: "gravitee_mongo_data"
  when: gravitee_mongo_data_infos.exists

