galaxy_info:
  author: C. Guychard <christophe@article714.org>, L. Rondel
  description: Install docker admin tools on a docker node (Portainer...)
  company: Article714

  license: LGPL

  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - system
    - docker
    - portainer
    - debian
    - ubuntu

dependencies:
  - role: docker-node
