#
# Ce petit playbook permet de gérer les serveurs Odoo sur un conteneur lxc
#
- name: Odoo Node on LXC with shared Postgresql
  hosts: OdooNodes
  remote_user: root
  become: true

  roles:
    - odoo-node
    #- nginxinc.nginx

  tasks:
    - name: redémarrage ODoo
      service:
        name: '{{ odoo_service }}'
        state: restarted

  vars:
    letsencrypt_enable: false
    nginx_http_template_enable: true
    nginx_main_template_enable: true
    nginx_main_template:
      error_level: warn
      http_enable: true
      http_global_autoindex: false
      port: 80
      stream_enable: false
      user: nginx
      worker_connections: 256
      worker_processes: auto
      http_settings:
        keepalive_timeout: 64
        cache: false
        rate_limit: false
        keyval: false
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: odoo_reverse.conf
        conf_file_location: /etc/nginx/conf.d/
        port: 80
        server_name: '{{ ODOO_SERVER_NAME }}'
        error_page: /usr/share/nginx/html
        autoindex: false
        worker_processes: auto
        reverse_proxy:
          locations:
            odoo:
              location: /
              proxy_pass: http://odoo_server
              proxy_redirect: off
              proxy_read_timeout: 720
              proxy_connect_timeout: 720
              proxy_send_timeout: 720
              # Add Headers for odoo proxy mode
              proxy_set_header:
                header_x_forwarded_host:
                  name: X-Forwarded-Host
                  value: '{{ ODOO_SERVER_NAME }}'
                header_x_forwarded_for:
                  name: X-Forwarded-For
                  value: $proxy_add_x_forwarded_for
                header_x_forwarded_proto:
                  name: X-Forwarded-Proto
                  value: $scheme
                header_x_real_ip:
                  name: X-Real-IP
                  value: $remote_addr
            odoo_chat:
              location: /longpolling
              proxy_pass: http://odoo_server_chat
              proxy_read_timeout: 720
              proxy_connect_timeout: 720
              proxy_send_timeout: 720
              # Add Headers for odoo proxy mode
              proxy_set_header:
                header_x_forwarded_host:
                  name: X-Forwarded-Host
                  value: '{{ ODOO_SERVER_NAME }}'
                header_x_forwarded_for:
                  name: X-Forwarded-For
                  value: $proxy_add_x_forwarded_for
                header_x_forwarded_proto:
                  name: X-Forwarded-Proto
                  value: $scheme
                header_x_real_ip:
                  name: X-Real-IP
                  value: $remote_addr
        upstreams:
          odoo:
            lb_method: least_conn
            groups:
              - odoo
            name: odoo_server
            zone_name: odoo
            zone_size: 64k
            sticky_cookie: false
            servers:
              docker_odoo_server:
                address: 127.0.0.1
                port: 8069
                weight: 1
                health_check: max_fails=3 fail_timeout=5s
          odoo_chat:
            lb_method: least_conn
            groups:
              - odoo
            name: odoo_server_chat
            zone_name: odoo_chat
            zone_size: 64k
            sticky_cookie: false
            servers:
              docker_odoo_server_chat:
                address: 127.0.0.1
                port: 8072
                weight: 1
                health_check: max_fails=3 fail_timeout=5s
