galaxy_info:
  author: C. Guychard <christophe@article714.org>
  description: Role to manage a Postgresql instance hosting Odoo databases
  company: Article714

  license: LGPL

  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - postgresql
    - docker
    - odoo

dependencies:
  - role: psql-server
