galaxy_info:
  author: C. Guychard <christophe@article714.org>
  description: Manage Proxy instances (Apache Traffic)
  company: Article714

  license: LGPL

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - system
    - workstation
    - debian
    - ubuntu
    - proxy
    - apache Traffic

dependencies:
  - { role: 'debian-based-container', when: machine_type == 'lxd' }
  - { role: 'debian-based-host', when: machine_type == 'host' }
  - role: ansible-role-systemd-networkd
