#
# Manage a HaProxy Server instance
#

- name: Manage LXD-Nodes
  hosts: LXDNodes
  remote_user: root
  become: true
  gather_facts: yes

  tasks:
    - name: LXD Node
      include_role:
        name: lxd-node
      when: machine_type == 'host'

  tags:
    - host_config

- name: Deploy and setup HaProxy
  hosts: HAProxyNodes
  remote_user: root
  become: true
  gather_facts: yes

  pre_tasks:
    - setup:
      when: machine_type == "host"

  roles:
    - haproxy-node

  tags:
    - ha_config
