- name: Update Network Configuration for Debian-based hosts
  hosts: DebianNodes
  remote_user: root
  become: true

  tasks:
    - name: Apply system config (LXD)
      include_role:
        name: debian-based-container
      when: machine_type == 'lxd'
    - name: Apply system config (Host)
      include_role:
        name: debian-based-host
      when: machine_type == 'host'
    - name: Apply network config
      include_role:
        name: ansible-role-systemd-networkd
      when: machine_type == 'host'
