- name: Update Software for Debian-based development stations
  hosts: DevWorkstations
  remote_user: root
  become: true

  #roles:
  #  - debian-based-workstation
  #  - ftps-server-node

  tasks:
    - name: Update Software for Debian hosts
      apt:
        upgrade: safe
        update_cache: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
