- name: Update Software for Debian-based hosts
  hosts: DebianNodes
  remote_user: root
  become: true

  roles:
    - ansible-role-systemd-networkd
    - debian-based-host

  tasks:
    - name: Update Software for Debian hosts
      apt:
        upgrade: safe
        update_cache: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
