#
# Manage a Webserver instances
#
- name: Manage LXD-Nodes
  hosts: LXDNodes
  remote_user: root
  become: true
  gather_facts: yes

  tasks:
    - name: LXD Node
      include_role:
        name: lxd-node
      when: machine_type == 'host'

  tags:
    - host_config

- name: Manage WebServers
  hosts: WebserverNodes
  remote_user: root
  become: true
  gather_facts: yes

  pre_tasks:
    - setup:
      when: machine_type == "host"

  roles:
    - webserver-node

  tags:
    - web_config
