---
- include: apply_nginx.yml
  when: http_server_flavor == 'nginx'

- include: apply_apache.yml
  when: http_server_flavor == 'apache'

- name: Set Up Firewall
  include: ufw_firewall.yml
  when: machine_type == 'host' and use_ufw
