---
- name: Update firewall rules (TCP) --> forwarded
  ufw:
    rule: '{{ item.rule }}'
    port: '{{ item.port }}'
    proto: tcp
    interface: '{{ proxy_in_interface }}'
    direction: '{{ item.dir }}'
    route: yes
  with_items:
    - { 'port': '{{ custom_proxy_http_port }}', 'dir': 'in', 'rule': 'allow' }
    - { 'port': '{{ custom_proxy_https_port }}', 'dir': 'in', 'rule': 'allow' }
  when: proxy_in_interface| default(false)

- name: Update firewall rules (TCP)
  ufw:
    rule: '{{ item.rule }}'
    port: '{{ item.port }}'
    proto: tcp
    interface: '{{ proxy_in_interface }}'
    direction: '{{ item.dir }}'
  with_items:
    - { 'port': '{{ custom_proxy_http_port }}', 'dir': 'in', 'rule': 'allow' }
    - { 'port': '{{ custom_proxy_https_port }}', 'dir': 'in', 'rule': 'allow' }
  when: proxy_in_interface| default(false)

- name: Reload Firewall
  ufw:
    state: reloaded
